-- ================================================
-- TVT Future Database Setup Script
-- Database: TVT_Future
-- SQL Server
-- ================================================

USE master;
GO

-- Create database if not exists
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'TVT_Future')
BEGIN
    CREATE DATABASE TVT_Future;
    PRINT 'Database TVT_Future created successfully!';
END
ELSE
BEGIN
    PRINT 'Database TVT_Future already exists!';
END
GO

USE TVT_Future;
GO

-- ================================================
-- Note: JPA will auto-generate tables based on entities
-- This script is for reference and manual setup if needed
-- ================================================

-- Check if tables exist
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Users')
BEGIN
    PRINT 'Tables already exist. JPA auto-generation is disabled.';
END
ELSE
BEGIN
    PRINT 'Tables will be auto-generated by JPA on first run.';
    PRINT 'Make sure persistence.xml has:';
    PRINT '<property name="jakarta.persistence.schema-generation.database.action" value="create"/>';
END
GO

-- ================================================
-- Sample Data (Optional - uncomment to insert)
-- ================================================

/*
-- Insert sample admin user (password is hashed)
INSERT INTO Users (username, password, role, createdAt) 
VALUES ('admin', 'hashed_password_here', 'Admin', GETDATE());

-- Insert sample models
INSERT INTO Models (modelName, brandId, year, seats) 
VALUES ('VF 3', 1, 2024, 5);

INSERT INTO Models (modelName, brandId, year, seats) 
VALUES ('VF 8', 1, 2024, 7);

-- Add more sample data as needed
*/

PRINT '================================================';
PRINT 'Database setup completed!';
PRINT 'Next steps:';
PRINT '1. Update persistence.xml with your SQL Server credentials';
PRINT '2. Start your Java web application';
PRINT '3. JPA will auto-generate tables on first run';
PRINT '================================================';
GO
